from django.contrib import admin
from .models import *

# Register your models here.

admin.site.register(ConfiguracionGeneral)
admin.site.register(Rol)
admin.site.register(Idioma)
admin.site.register(Tema)
admin.site.register(Usuario)
admin.site.register(Visita)
admin.site.register(DialogoPersonaje)
admin.site.register(Desafio)
admin.site.register(UsuarioProgresoDesafio)
admin.site.register(Zona)
admin.site.register(Color)
admin.site.register(TipoRecurso)
admin.site.register(MultimediaZona)
admin.site.register(Exhibicion)
admin.site.register(Objetivo)
admin.site.register(PaginaExhibicion)
admin.site.register(Escaneo)
admin.site.register(Interaccion)
admin.site.register(Opinion)
admin.site.register(Emoji)
admin.site.register(Publicacion)
admin.site.register(Reaccion)
admin.site.register(Favorito)
admin.site.register(Notificacion)
admin.site.register(Preferencia)